function greet(name) {
    const words = ["Hello",
        "Hola",
        "Bonjour",
        "Ciao",
        "Olá",
        "Hallo",
        "Hej",
        "Hei",
        "Здравствуйте",
        "Cześć",
        "Ahoj",
        "Szia",
        "Bună",
        "Здравейте",
        "Γειά σου",
        "Merhaba",
        "مرحبا",
        "שלום",
        "سلام",
        "नमस्ते",
        "হ্যালো",
        "سلام",
        "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
        "નમસ્તે",
        "नमस्कार",
        "வணக்கம்",
        "హలో",
        "నమస్తే",
        "ನಮಸ್ಕಾರ",
        "നമസ്‌കാരം",
        "හෙලෝ",
        "සวัสดี",
        "Xin chào",
        "Halo",
        "Helo",
        "Kamusta",
        "Habari",
        "Sawubona",
        "Molo",
        "ሰላም",
        "Iska warran",
        "नमस्ते",
        "Slaw",
        "Salom",
        "Сәлеметсіз бе",
        "Сайн байна уу"]
    const rand = Math.round(Math.random() * (words.length - 1))
    
    return `${words[rand]}${name ? ` ${name}!` : "!"}`
}

module.exports = {
    greet
}